### ISSUE TITLE
not installable from Google Play

### ISSUE THREAD

**Issue by pat1** [tiagoshibata/Android-GPSd-Client#21] opened 2023-12-10 15:45 UTC
We are going to use this app in a open project https://rmap.cc/ https://github.com/r-map using udp packets from ESP32 micro controller boards for geolocalization of environmental data.
We have to propose the use of the app in schools at students and teachers; the app is installable from Fdroid but we have tried to install it from Google Play from some different phone (old and new) and it was not possible (not supported device); this will be a problem for a large number of users.
It's possible it need a rebuild?

Thanks for your work!

**Comment by tiagoshibata** [comment] 2024-10-14 01:38
Sorry, I haven't been active on GitHub.

Google changed minimum SDK version requirements, making so old builds can't be installed on newer phones. The current build can only be installed from F-Droid, as you figured out.

I'd gladly review and validate a PR using a newer SDK. Else, it'll be in my "whenever I have time" bucket.

**Comment by tiagoshibata** [comment] 2024-10-14 01:40
Duplicate of #18

**Closed as completed by tiagoshibata** 2024-10-14 01:40 UTC
